[package]
name = "minigrep"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3"
rayon = "1.10.0"
aho-corasick = "1.1.3"
colored="2.1.0"
regex="1.10.5"
lazy_static = "1.4.0"
memmap2="0.9.4"

